### ISSUE TITLE
AltGr -> request or correction

### ISSUE THREAD

**Issue by Kraker23** [ahkohd/switch-desktop#25]
Hi,
First of all the program is very good. My congratulations.
Only one request or correction, when you use the ALTGr +2 to put the @ or any special character of need of AltGr, the program you have in that number opens.
I find two solutions say in the configuration if you want to use the AltGr as Alt or not, or have it detect that if it is AltGr do not take it into account.

**Comment by ahkohd** [comment]
Thanks for reaching out, I have taken this into consideration. The next release will option to disable Switch listening to AltGr + 2 at the settings window.

**Comment by Kraker23** [comment]
Thanks for your consideration, but not only with AltGr+2, this is with all combination with AltGr + number.

Congratulations for your project.

**Comment by ahkohd** [comment]
@Kraker23  Thanks for your feedback, Switch v1.0.18 now gives the option of disabling app switching with AltGr.
