### ISSUE TITLE
Stolen assets from Wexond (wexond.net)

### ISSUE THREAD

**Issue by EnderDev** [ahkohd/switch-desktop#26]
Hello. It has come to my attention that the website associated with Switch Desktop (https://ahkohd.github.io/switch-desktop/) uses the same design as Wexond.

![eDp5k0J 1](https://user-images.githubusercontent.com/42723993/64906233-d0c0f800-d6db-11e9-8f31-a1bf511acf68.png)

![tiU1UHl 1](https://user-images.githubusercontent.com/42723993/64906279-55137b00-d6dc-11e9-89d4-c2e434c406c8.png)

They look very similar. Not only that, you use a similar README to Wexond.

# **Switch**
![OBBNpiy 1](https://user-images.githubusercontent.com/42723993/64906285-75433a00-d6dc-11e9-88e1-0207acee3b18.png)

This part in particular looks almost identical to Wexond's README

 # **Wexond**
![cw4Rd4I 1](https://user-images.githubusercontent.com/42723993/64906291-9572f900-d6dc-11e9-8fe7-b54ec13dfdeb.png)

Archived version. _https://web.archive.org/web/20190914093906/https://ahkohd.github.io/switch-desktop/_

**Comment by laemongrass** [comment]
You're logo is very similar too, especially the colour scheme. It's uncanny.

**Comment by ahkohd** [comment]
Wow, Wexnod was a source of inspiration while I was developing this project and therefore this project was heavily influenced by Wexnod. I have no intentions of stealing assets and I sincerely apologize for any conflict this as caused. I will, therefore and redo Switch's branding and color scheme as soon as possible. Thanks

**Comment by sentialx** [comment]
I have been told about this issue, but I don't see anything wrong with using similar color schemes (honestly I can't see that they're the same). There's nothing wrong with being inspired by someone's work.

**Comment by EnderDev** [comment]
Thank you @ahkohd

**Comment by ahkohd** [comment]
> I have been told about this issue, but I don't see anything wrong with using similar color schemes (honestly I can't see that they're the same). There's nothing wrong with being inspired by someone's work.

@sentialx , you inspired me to build **Switch**. Can't thank you enough lookin for more ways to contribute man.

**Comment by ahkohd** [comment]
Anyways to avoid future conflict, I am in the process of developing a new homepage. WIP when am done with this I will close this issue.
