### ISSUE TITLE
Severe! Can not use

### ISSUE THREAD

**Issue by osrich** [ahkohd/switch-desktop#28]
Windows Version: Windows 10 professional

After install Switch, and add some apps into the dock, press shortcut keys alt+1/2/3, notification pops out below: it seems like *** is yet to be opened...

but the app is running already! No matter how i alter the shortcutkeys, keeps poping out the notification...
![Snipaste_2019-09-16_11-10-42](https://user-images.githubusercontent.com/55370127/64932576-ab1a2700-d872-11e9-9888-242386d79c26.jpg)
![Snipaste_2019-09-16_11-11-21](https://user-images.githubusercontent.com/55370127/64932585-b9684300-d872-11e9-80a9-6bab58afa387.jpg)

Don't know what's the problem but it feels pretty bad....

**Comment by ahkohd** [comment]
Thanks for reaching out @osrich This is a known issue with Microsoft Office apps and its  because  the exe is some kind of a launcher that launches  the appropriate appropriate office app which is kind of trivial track by Switch.

**Comment by ahkohd** [comment]
Very well, I am in the process of fixing this by creating some kind 0f special case process search for apps that behaves like this. Please try using other switchable apps for the main time while I try to fix this. Thanks!

**Comment by ahkohd** [comment]
@osrich am glad that this issue has been fixed a new update is coming tonight.

**Comment by ahkohd** [comment]
@osrich Once again thanks for reaching out. This issue has been fixed not only for Microsoft Office apps but also this fix works for any apps that have similar behavior. dfc9a73
  
![switch-tease-fix2](https://user-images.githubusercontent.com/13041443/64999953-a0e34180-d8e1-11e9-9e10-3197ec09763f.gif)

**Comment by osrich** [comment]
@ahkohd Great! Thanks for prompt endeavor!
