### ISSUE TITLE
support software blacklist

### ISSUE THREAD

**Issue by zhaojinpeng111** [ahkohd/switch-desktop#31]
how about support software blacklist or ignore some sofeware?

**Comment by ahkohd** [comment]
@zhaojinpeng111 thanks for reaching out. If you don't need to Switch an app then just don't put it on the dock or do you have a blacklist use case.

**Comment by zhaojinpeng111** [comment]
> @zhaojinpeng111 thanks for reaching out. If you don't need to Switch an app then just don't put it on the dock or do you have a blacklist use case.

I mean in some app it doesn't work

Forexample In webstorm, it conflict with webstorm default keymap

**Comment by ahkohd** [comment]
Hmm, I noted. But you could remap the keys.
