### ISSUE TITLE
Can't add apps to the switch bar on MacOS Mojave 10.14.6

### ISSUE THREAD

**Issue by Samuel-CTI** [ahkohd/switch-desktop#46]
Hi
I wanted to give your application a try since switching between applications on mac is a nightmare.
My issue is that I am unable to add applications to the switch bar. When I click the `+` icon on the dock, the finder window that appears does not allow me to select `.app` applications, it treats them as a folder and opens their contents rather than selecting them for switch.

Tested on: MacOS Mojave 10.14.6

**Comment by Samuel-CTI** [comment]
Would it be possible to add these applications to the config file manually, while this is fixed?
Is there a yaml or json that I could edit?

**Comment by ahkohd** [comment]
Hey, thanks for reaching out. I forgot to specify in the documentation that if you use the mac version, you have to select the `PkgInfo` file in the folder of the app you want to add. 
Here is a quick demo.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13041443/74159494-2c0bfd80-4c1c-11ea-81a4-d5dbba7f7fb8.gif)
